### ISSUE TITLE
adaptive flag - where to enter estimated overlap

### ISSUE THREAD

**Issue by peptiderodriguez** [VasylVaskivskyi/biostitch#11]
Hi all,
I'm using biostitch to stitch Opera Phenix scans of tissue immunofluorescence. I am trialing different % overlaps on the microscope to see which gives me the best stitched images. The help for the adaptive flag in biostitch says that I should pass the estimated overlap, but in the example there is no estimated overlap that is passed, and when I try to pass something like "0.2", the program complains about an unrecognized argument. Is there another way/place to enter the % overlap?
Thanks!

**Comment by VasylVaskivskyi** [comment]
Hi @peptiderodriguez please use BigStitcher instead or licensed sticher from Perkin Elmer.
This project is abandoned because of quirks with Perkin Elmer metadata and me not willing to waste more time on it.
Anyway, I think it was a mistake in documentation, and you just need to add `--adaptive` without providing values.

**Comment by peptiderodriguez** [comment]
Thanks for the quick reply! Their metadata is indeed a mess!
Best,
Edwin
